#!/bin/sh

PIDFILE=/var/run/backup-run.pid

if [ -f $PIDFILE ]; then
	echo $0 is already running with pid $(cat $PIDFILE), aborting!
	exit 1
fi

if [ ! -x /usr/local/bin/backup-${BACKUP_METHOD} ]; then
	echo Backup Method ${BACKUP_METHOD} does not exists!
	exit 1
fi

echo $$ >$PIDFILE

/usr/local/bin/backup-${BACKUP_METHOD} ${BACKUP_OPTS}

retval=$?

rm $PIDFILE

exit $retval
